# Generated by Django 4.0.3 on 2022-04-11 13:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_body', models.TextField(max_length=5000)),
                ('article_title', models.CharField(max_length=100)),
                ('article_category', models.CharField(max_length=10)),
                ('add_time', models.DateTimeField(default=datetime.datetime(2022, 4, 11, 21, 10, 5, 214544), verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('owner_nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_article',
            },
        ),
    ]
